spring:
  servlet:
    multipart:
      max-file-size: 3GB
      max-request-size:  3GB

  datasource:
    url: jdbc:mysql://localhost:3306/TeaManagement
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

  resources:
    static-locations: file:uploads/

file:
  uploadDir: D:/Tea _Store_Management/Tea_Store_Management_Frontend/Tea-Store-Management-frontend/src/assets/backend



